site_name: Elyse Amadei
use_directory_urls: false
site_description: "Elyse Amadei, créatrice d'accessoires de mode faits main en France."

theme:
  name: material
  language: fr
  palette:
    primary: black
  logo: assets/logo/monogramme_EA_inverted.png
  favicon: assets/logo/favicon.ico
  features:
    - navigation.index
    - navigation.tabs
    - toc.integrate
  custom_dir: theme_overrides

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://fr.linkedin.com/in/elyse-amadei-37842488
      name: Elyse Amadei on LinkedIn
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/elyseamadei
      name: Elyse Amadei on Instagram
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/Elyse-Amadei-Cr%C3%A9atrice-Accessoires-de-mode-1432345936995681/
      name: Elyse Amadei on Facebook

copyright: Copyright &copy; 2005-2023 Elyse Amadei

nav:
  - Nos Créations: index.md
  - Le Catalogue: assets/Catalogue Elyse AMADEI 2023.pdf
  - Optique:
    - Cordons Adultes: cordons_adultes.md
  #   - Cordons Chic'alors: cordons_chic_alors.md
  #   - Cordons Les Amis: cordons_amis.md
  #   - Cordons Enfants: cordons_engants.md
  #   - Chaînettes Mailles: chainettes_mailles.md
  #   - Colliers: colliers.md
  # - Bracelets:
  #   - Magic' Trilogy: magic_trilogy.md
  #   - Pierres Uniques: pierres_uniques.md
  #   - Les vertues des pierres: vertues.md
  - Bracelets: bracelets.md
  - La Créatrice: creatrice.md
  - Nous Contacter: contact.md

# https://facelessuser.github.io/pymdown-extensions/extensions/progressbar/
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.mark
  - pymdownx.progressbar:
      level_class: false
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - glightbox

hooks:
  - bracelets.py
  - cordons.py
